### ISSUE TITLE
Syntax Error on js.lua

### ISSUE THREAD

**Issue by mast-maula-mihir** [MrcSnm/Love.js-Api-Player#3]

**Comment by mast-maula-mihir** [comment]
![image](https://user-images.githubusercontent.com/60816002/156567908-58db025e-b436-47ef-8284-3e3165200382.png)
In the above image, syntax error from line 154 to line 158.

**Comment by mast-maula-mihir** [comment]
![image](https://user-images.githubusercontent.com/60816002/156568535-90a98cb7-b20e-4c88-b0c8-93103957c0e0.png)
This is the error we're getting.

**Comment by mast-maula-mihir** [comment]
![image](https://user-images.githubusercontent.com/60816002/156571730-76da32b2-7cfa-407b-97aa-852545337499.png)
Thanks for changing the code, however, I think this is what should be the correct one.

**Comment by MrcSnm** [comment]
Post a minimal example containing the error plz

**Comment by MrcSnm** [comment]
Fixed

**Comment by mast-maula-mihir** [comment]
![image](https://user-images.githubusercontent.com/60816002/156572627-869ea28f-5622-40fc-9267-789a2a37c038.png)
In the recent update you missed a comma in the code. Please update the same in the repo. It should be
JS.callJS(JS.stringFunc(
    [[
        __getWebDB("%s");
    ]]
,"__LuaJSDB"))

**Comment by mast-maula-mihir** [comment]
Thanks for fixing it!

**Comment by mast-maula-mihir** [comment]
Do we need to download and include consolewrapper.js in the index.html in order for the JS.callJS() to work?

**Comment by mast-maula-mihir** [comment]
![image](https://user-images.githubusercontent.com/60816002/156574156-a4f1d7b9-4049-4514-9b6d-0655d52d6ee9.png)
We tried to run this code, but we got the following thing in the console.
![image](https://user-images.githubusercontent.com/60816002/156574277-dd7d6ebf-a81a-4585-86ae-29e01a37c611.png)
Instead of giving output 20, it prints out the entire thing written inside the [[]]

**Comment by MrcSnm** [comment]
> Do we need to download and include consolewrapper.js in the index.html in order for the JS.callJS() to work?

Yes, that is exactly how it works, include it on the index.html.
